### ISSUE TITLE
Parsing data exception

### ISSUE THREAD

**Issue by ne1llee** [jimporter/bencode.hpp#9] opened 2024-08-01 08:20 UTC
## data string
```
d8:msg_typei1e5:piecei0e10:total_sizei93eed6:lengthi1453e4:name15:31234123123.txt12:piece lengthi16384e6:pieces20:\276߅{\036\331\303\352FY\035\204\202\334LT\263/\227ie
```
## data hex
```
 64 38 3a 6d 73 67 5f 74 79 70 65 69 31 65 35 3a
 70 69 65 63 65 69 30 65 31 30 3a 74 6f 74 61 6c
 5f 73 69 7a 65 69 39 33 65 65 64 36 3a 6c 65 6e
 67 74 68 69 31 34 35 33 65 34 3a 6e 61 6d 65 31
 35 3a 33 31 32 33 34 31 32 33 31 32 33 2e 74 78
 74 31 32 3a 70 69 65 63 65 20 6c 65 6e 67 74 68
 69 31 36 33 38 34 65 36 3a 70 69 65 63 65 73 32
 30 3a be df 85 7b 1e d9 c3 ea 46 59 1d 84 82 dc
 4c 54 b3 2f 97 69 65
```

**Comment by jimporter** [comment] 2024-08-01 14:59
This works for me. Could you be more specific about the error you're getting?

**Comment by ne1llee** [comment] 2024-08-02 02:56
![image](https://github.com/user-attachments/assets/4ed034ab-20aa-4fb1-aad0-82563cb523f3)
There is an error in processing this kind of nested dictionary. I wonder if my usage is wrong?

**Comment by jimporter** [comment] 2024-08-02 04:22
@ne1llee Unfortunately, that doesn't show what the error message is, but as a guess, it might be something like this: `extraneous character, at offset 42`. The offset matches what your screenshot shows anyway.

If that's correct, then I believe the issue is due to the fact that your bencoded data isn't a single object, but two separate ones, one right after the other. It's 100% ok to have multiple bencoded objects in a single string or stream like that, but you'll have to decode them separately. If you're using the latest revisions from this repository, you'll need to use the `decode_some` function to do this; that function will decode a single bencoded object and return it, updating the pointer, iterator, stream, etc that you passed in so that the next time you call `decode_some`, you get the next object.

For your example, you could do something like this:
```c++
auto current = data.begin();
// Get the first object:
auto decoded_data_1 = bencode::decode_some(current, data.end());
// Now `current` should be at the beginning of the second object.

// Get the second object, method 1:
auto decoded_data_2 = bencode::decode(current, data.end());
// Get the second object, method 2:
auto decoded_data_2 = bencode::decode_some(current, data.end());
assert(current == data.end());
```

Below, I've split up the bencoded data you posted in your first comment into separate strings so that it's hopefully easier to see how this is two separate objects. (This is usually how I write bencoded data in the unit tests, since I find it much easier to read, and then I can often understand the data just by looking at it.)

```
"d"
  "8:msg_type"  "i1e"
  "5:piece"  "i0e"
  "10:total_size"  "i93e"
"e"
"d"
  "6:length"  "i1453e"
  "4:name"  "15:31234123123.txt"
  "12:piece length"  "i16384e"
  "6:pieces"  "20:\276߅{\036\331\303\352FY\035\204\202\334LT\263/\227i"
"e"
```

EDIT: One more thing... based on your example code, maybe you really want to treat this as a single bencoded object. In that case, your code is working properly: it's rejecting some improperly-formatted data. If that's just some test data you're using to try out your code, hopefully the human-readable version of the data above will help you out.

**Comment by ne1llee** [comment] 2024-08-06 05:43
![image](https://github.com/user-attachments/assets/0123c305-37c7-4605-9a99-a33ec1833bfc)

@jimporter Thanks for the answer. These are indeed two pieces of data. They can be parsed normally using bencode::decode_some.

**Comment by jimporter** [comment] 2024-08-06 18:58
Glad to hear it. Since it sounds like this is all working for you now, I'm closing this bug. If you see other issues though, just let me know and we can discuss more.

**Closed as completed by jimporter** 2024-08-06 18:58 UTC
